### ISSUE TITLE
message to Manfred-Knick

### ISSUE THREAD

**Issue by guidocella** [guidocella/dwl#4]
@Manfred-Knick I rebased my patches on May 3, but your email server rejected my email reply. Sorry if my patches fall out of date, but I went back to dwm a couple of years ago.

**Comment by Manfred-Knick** [comment]
-------- Weitergeleitete Nachricht --------
Betreff: [ dwl : shiftview ] /* tagging */ / 3. : confirm / download label
Datum: Wed, 17 May 2023 22:40:01 +0200
Von: Manfred_Knick ***@***.***>
Antwort an: ***@***.***
An: Guido Cella ***@***.***>

Hi, Guido,

this is to confirm about gentoo versions

  =gui-wm/dwl-9999:0     # req. wlroots:0/16
  =gui-wm/dwl-9999-r1:0  # req. wlroots:0/9999 and media-libs/libdisplay-info


So now, I am successfully running

	# dwl -v

	dwl v0.4-38-g2d1a40c-dirty


Thank you once again!


HINT:


Your old patch still being needed for dwl-0.4 is not available any more.

Your new patch resides under the old date:

	"Download"

		"2022-07-06"

[ https://github.com/djpohly/dwl/wiki/shiftview ]



Kind regards from Munich!

Manfred
